classdef ColormapList
    % This class enumerates the available colormaps of a system.
    % It is auto-generated by the function rewriteColormapList.
    % Manual changes will be overriden the next time rewriteColormapList is called.

    enumeration
        Parula (parula(256))
        Jet (jet(256))
        Hsv (hsv(256))
        Hot (hot(256))
        Cool (cool(256))
        Spring (spring(256))
        Summer (summer(256))
        Autumn (autumn(256))
        Winter (winter(256))
        Gray (gray(256))
        Bone (bone(256))
        Copper (copper(256))
        Pink (pink(256))
        Blue (phutils.colormaps.blue(256))
        Cyan (phutils.colormaps.cyan(256))
        Green (phutils.colormaps.green(256))
        Hotandblue (phutils.colormaps.hotandblue(256))
        Irish (phutils.colormaps.irish(256))
        Magenta (phutils.colormaps.magenta(256))
        Red (phutils.colormaps.red(256))
        Yellow (phutils.colormaps.yellow(256))
        Greenwhite (phutils.colormaps.custom.greenwhite(256))
        Redwhite (phutils.colormaps.custom.redwhite(256))
        Yellowwhite (phutils.colormaps.custom.yellowwhite(256))
    end % enumeration
 
    properties( SetAccess = immutable, Transient )
        Map % the colormap data
    end %properties
 
    methods
        function self = ColormapList( map )
            self.Map = map;
        end % Constructor
    end %methods
end % classdef
