function set_setting(varargin)
%PHUTILS.SET_SETTING Sets and stores a setting
%
% PHUTILS offers a simple system to store and retrieve settings. You can
% set setting `key` to `val` with the following:
%
%   setting = phutils.set_setting(key, val);
%
% key must be a valid struct fieldname. If key is already known, the
% setting is updated. Otherwise, it is created.
%
% See also: phutils.get_setting phutils.delete_setting
    assert(mod(nargin, 2) == 0, 'phutils:BadArgument', ...
        'Arguments for phutils.set_setting must come in pairs.');
    try
        loaded_data = load(...
            fullfile(...
                phutils.get_user_applicationdir('phutils', true, true),...
                'settings.mat'...
            ), ...
            'phutils_settings'...
        );
    catch
        loaded_data = struct('phutils_settings', struct());
    end
    phutils_settings = loaded_data.phutils_settings;
    for i = 1:2:nargin 
        phutils_settings.(varargin{i}) = varargin{i+1};
    end
    save(...
        fullfile(...
            phutils.get_user_applicationdir('phutils'),...
            'settings.mat'...
        ), ...
        'phutils_settings' ...
    );