function rewriteColormapList()
% this function rewrites the enumeration class
% phutils.colormaps.ColormapList
%
% It looks for any lowercase function in phutils.colormaps.* and
% phutils.colormaps.custom.* and generates the enumeraion class from it.
%
% It omits the non-linear colormaps delivered by Matlab

    ml_cm = {'parula', 'jet', 'hsv', 'hot', 'cool', ...
        'spring', 'summer', 'autumn', 'winter', ...
        'gray', 'bone', 'copper', 'pink'};
    
    str = {...
'classdef ColormapList', ...
'    % This class enumerates the available colormaps of a system.',...
'    % It is auto-generated by the function rewriteColormapList.',...
'    % Manual changes will be overriden the next time rewriteColormapList is called.',...
'', ...
'    enumeration'};
    str2 = { ...
'    end % enumeration',  ...
' ' ...
'    properties( SetAccess = immutable, Transient )' ...
'        Map % the colormap data' ...
'    end %properties' ...
' ' ...
'    methods' ...
'        function self = ColormapList( map )' ...
'            self.Map = map;'....
'        end % Constructor' ...
'    end %methods' ...
'end % classdef'};

    filename = mfilename('fullpath');
    parts = strsplit(filename, filesep);
    
    % Omit two last elements (+tools and filename)
    parts = parts(1:end-2);
    path = fullfile(filesep, parts{:});
    d = dir(fullfile(path, '*.m'));
    
    cms = {};
    for cm = ml_cm
        cm = cm{1};
        cms{end+1} = ['        ' upper(cm(1)) cm(2:end) ' (' cm '(256))'];
    end
    for file = d'
        [~,fname, ~] = fileparts(file.name);
        % avoid file names starting with an uppercase letter
        if ~strcmp(upper(fname(1)), fname(1))
            cms{end+1} = ['        ' upper(fname(1)) fname(2:end) ' (phutils.colormaps.' fname '(256))'];
        end
    end
    d = dir(fullfile(path, filesep, '+custom', '*.m'));
    for file = d'
        [~,fname, ~] = fileparts(file.name);
        % avoid file names starting with an uppercase letter
        if ~strcmp(upper(fname(1)), fname(1))
            cms{end+1} = ['        ' upper(fname(1)) fname(2:end) ' (phutils.colormaps.custom.' fname '(256))'];
        end
    end
    
    % (Try to) make a backup copy of the original file
    try
        movefile(fullfile(path, 'ColormapList.m'), fullfile(path, 'ColormapList.bak'));
    catch e
    end
    
    fid = fopen(fullfile(path, 'ColormapList.m'), 'w');
    local_print_cell(fid, str);
    local_print_cell(fid, cms);
    local_print_cell(fid, str2);
    fclose(fid);
end

function local_print_cell(fid, c)
    cellfun(@(x)(fprintf(fid, '%s\n', x)), c);
end